name: Unit

on:
  push:
    branches: [master]
    paths:
      - .github/workflows/programs-unit.yml
      - programs/**
      - Cargo.toml
      - Cargo.lock
  pull_request:
    branches: [master]
    paths:
      - .github/workflows/programs-unit.yml
      - programs/**
      - Cargo.toml
      - Cargo.lock

defaults:
  run:
    shell: nix shell .#rust --command bash {0}

env:
  CARGO_TERM_COLOR: always

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v17
      - name: Setup Cachix
        uses: cachix/cachix-action@v12
        with:
          name: goki
          extraPullNames: quarry, saber
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - uses: Swatinem/rust-cache@v1
      - name: Run fmt
        run: cargo fmt -- --check
      - name: Run clippy
        run: cargo clippy --all-targets -- --deny=warnings
      - name: Check if publish works
        run: cargo publish --no-verify --dry-run

  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v17
      - name: Setup Cachix
        uses: cachix/cachix-action@v12
        with:
          name: goki
          extraPullNames: quarry, saber
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - uses: Swatinem/rust-cache@v1
      - name: Run unit tests
        run: cargo test --lib

  doc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v17
      - name: Setup Cachix
        uses: cachix/cachix-action@v12
        with:
          name: goki
          extraPullNames: quarry, saber
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - uses: Swatinem/rust-cache@v1
      - name: Generate docs
        run: cargo doc
